version: '3.3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    restart: always
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: dinarchik28/foodgram_backend:latest
    restart: always
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/staticfiles
      - media_volume:/media
      - ./data/:/app/data/

  frontend:
    image: dinarchik28/kittygram_frontend:latest
    restart: always
    volumes:
      - ./frontend/:/app/result_build/
  nginx:
    image: nginx:1.25.4-alpine
    restart: always
    depends_on:
      - backend
      - frontend
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/staticfiles
      - media_volume:/media