name: Main Tasyideas workflow

on: push

jobs:
  build_and_push_backend:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_NICK }}/foodgram_backend:latest

  build_and_push_frontend:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v4
        with:
          context: ./frontend/
          push: true
          tags: ${{ secrets.DOCKER_HUB_NICK }}/foodgram_frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build_and_push_backend
      - build_and_push_frontend
    steps:
      - uses: actions/checkout@v3

      - name: Prepare deploy archive
        run: |
          mkdir -p deploy
          cp infra/docker-compose.yml deploy/
          cp infra/nginx.conf deploy/
          cp -r docs deploy/
          tar -cvf deploy.tar -C deploy .

      - name: Copy deploy archive to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "deploy.tar"
          target: "foodgram"

      - name: Execute remote deploy commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd foodgram
            tar -xvf deploy.tar
            rm deploy.tar
            sudo docker compose pull
            sudo docker compose down
            sudo docker compose run --rm frontend npm run build
            sudo docker compose up -d
            sudo docker compose exec backend python manage.py migrate
            sudo docker compose exec backend python manage.py collectstatic --noinput

  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅ Деплой Foodgram выполнен!
            Автор: ${{ github.actor }}
            Коммит: ${{ github.event.head_commit.message }}
            https://github.com/${{ github.repository }}/commit/${{ github.sha }}
